name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: list
        uses: ./
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          owner: pulumi
          repo: registry
      - run: echo ${{ steps.list.outputs.titles }}
